book_info = {
    '1': {
        'id': '1',
        'title': 'The Moon and Sixpence',
        'coverImage': 'https://images-na.ssl-images-amazon.com/images/I/513gvH48ziL._SX322_BO1,204,203,200_.jpg',
        'year': '1919',
        'summary': 'First published in 1919, W. Somerset Maugham’s “The Moon and Sixpence” is an episodic first person narrative based on the life of Paul Gaugin. At the center of the novel is the story of Charles Strickland, an English banker who walks away from a life of privilege, abruptly abandoning his wife and children, in order to pursue his passion to become an artist. Strickland leaves London for Paris and ultimately Tahiti, mirroring the life of Gaugin who would also split with his wife to pursue a life of painting eventually immigrating to Tahiti. The title of the novel, which is never clearly explained in the novel, comes from a review for Maugham’s previous work “Of Human Bondage” in which that novel’s protagonist, Philip Carey, is described as “so busy yearning for the moon that he never saw the sixpence at his feet.” The moon in this sense might be seen as the lofty ambition to pursue a life of artistic expression in contrast to the sixpence which represents the security of a middle-class life style with wife and children to which the protagonist abandons. “The Moon and Sixpence” is the story of the demands that can be placed on a tortured artistic soul and consequently the lives that it touches. This edition is printed on premium acid-free paper.',
        'author': 'W. Somerset Maugham',
        'price': '$6.99',
        'score': '4.4',
        'genre': ['Novel', 'Biography', 'Psychological'],
        'publisher': 'Digireads.com Publishing',
        'language': 'English'
    },
    '2': {
        'id': '2',
        'title': 'Of Human Bondage',
        'coverImage': 'https://images-na.ssl-images-amazon.com/images/I/51fQkydyOXL._SX303_BO1,204,203,200_.jpg',
        'year': '1915',
        'summary': "Of Human Bondage is the first and most autobiographical of Maugham's novels. It is the story of Philip Carey, an orphan eager for life, love and adventure. After a few months studying in Heidelberg, and a brief spell in Paris as a would-be artist, Philip settles in London to train as a doctor. And that is where he meets Mildred, the loud but irresistible waitress with whom he plunges into a formative, tortured and masochistic affair which very nearly ruins him.",
        'author': 'W. Somerset Maugham',
        'price': '$5.95',
        'score': '4.2',
        'genre': ['Semi-autobiographical', 'Novel'],
        'publisher': 'Bantam Classics; Reprint edition',
        'language': 'English'
    },
    '3': {
        'id': '3',
        'title': 'Norwegian Wood',
        'coverImage': 'https://m.media-amazon.com/images/I/51LM40PeVCL.jpg',
        'year': '1987',
        'summary': "Stunning and elegiac, Norwegian Wood first propelled Haruki Murakami into the forefront of the literary scene.Toru, a serious young college student in Tokyo, is devoted to Naoko, a beautiful and introspective young woman, but their mutual passion is marked by the tragic death of their best friend years before. As Naoko retreats further into her own world, Toru finds himself drawn to a fiercely independent and sexually liberated young woman. A magnificent coming-of-age story steeped in nostalgia, Norwegian Wood blends the music, the mood, and the ethos that were the '60s with a young man's hopeless and heroic first love. ",
        'author': 'Haruki Murakami',
        'price': '$12.99',
        'score': '4.7',
        'genre': ['Love', 'Novel', 'Sentimental', 'Lonely'],
        'publisher': 'Random House Audio',
        'language': 'Japanese'
    },
    '4': {
        'id': '4',
        'title': 'Kafka on the Shore',
        'coverImage': 'https://m.media-amazon.com/images/I/51YcbO1nGUL.jpg',
        'year': '2002',
        'summary': 'With Kafka on the Shore, Haruki Murakami gives us a novel every bit as ambitious and expansive as The Wind-Up Bird Chronicle, which has been acclaimed both here and around the world for its uncommon ambition and achievement, and whose still-growing popularity suggests that it will be read and admired for decades to come.',
        'author': 'Haruki Murakami',
        'price': '$12.99',
        'score': '4.2',
        'genre': ['Novel', 'Ethics'],
        'publisher': 'Random House Audio',
        'language': 'Japanese'
    },
    '5': {
        'id': '5',
        'title': 'The Old Man and the Sea',
        'coverImage': 'https://m.media-amazon.com/images/I/515CFohKs4L.jpg',
        'year': '1952',
        'summary': 'Santiago es un viejo pescador cubano que ya lleva ochenta y cuatro días sin coger un solo pescado. Sólo tiene un amigo, el joven Manolin su aprendiz, a quien sus padres sin embargo fuerzan a que dejen de ir con el viejo Santiago porque dicen: ya no tiene suerte.Sin embargo Manolin sigue ayudando a su amigo Santiago todos los días cuando llega de su infructuosa pesca.En el día que hace ochenta y cinco Santiago sale con su pequeño esquife y se adentra en el mar, alejándose de las aguas costeras. Entrando ya en la corriente del Golfo, prepara los sedales y tras haber conseguido carnaza los deja que desciendan casi cien brazas. A mediodía siente que ha picado un gran pez y está seguro de que es un hermoso pez espada. Usando de la experiencia de toda una vida comienza una lucha entre Santiago y el pez que dura cerca de tres días.Santiago es la personificación de la lucha contra el fracaso. Nunca se da por vencido. Deberíamos aprender de el.',
        'author': 'Ernest Hemingway',   
        'price': '$11.58',
        'score': '4.8',
        'genre': ['Modernism', 'Conte', 'Inner monologue'],
        'publisher': 'Sonolibro',
        'language': 'Spanish'
    },
    '6': {
        'id': '6',
        'title': 'The Million Pound Bank Note',
        'coverImage': 'https://m.media-amazon.com/images/I/510uMgaB8bL.jpg',
        'year': '1893',
        'summary': 'The story takes place in Victorian London, where two very rich, eccentric brothers give the penniless story protagonist, Henry Adams, one million pounds of money in the form of a single peerless bank note. Henry would not be easily able to exchange that note in the bank without being questioned about how he had come to it, charged with theft and arrested. He would also not be able to spend it since no ordinary person would be able to change it.Without knowing it, Henry is the subject of a bet: Oliver believes that the mere possession of this symbol of wealth will enable anyone to have anything he wants, without actually cashing the note. Roderick, on the other hand, feels that the prohibition against exchanging the note for cash will render it totally useless',
        'author': 'Mark Twain',
        'price': '$23.96',
        'score': '4.2',
        'genre': ['Novella', 'Humor', 'Satire'],
        'publisher': 'Page2Page',
        'language': 'English'
    },
    '7': {
        'id': '7',
        'title': 'The Adventures of Tom Sawyer',
        'coverImage': 'https://m.media-amazon.com/images/I/61OhDUE9CKL.jpg',
        'year': '1876',
        'summary': "A natural storyteller and raconteur in his own right - just listen to Paddle Your Own Canoe and Gumption - actor, comedian, carpenter, and all-around manly man Nick Offerman (Parks and Recreation) brings his distinctive baritone and a fine-tuned comic versatility to Twain's writing. In a knockout performance, he doesn't so much as read Twain's words as he does rejoice in them, delighting in the hijinks of Tom - whom he lovingly refers to as a \"great scam artist\" and \"true American hero\" - while deftly delivering the tenderness and care Twain gave to his own characters.",
        'author': 'Mark Twain',
        'price': '$9.39',
        'score': '4.5',
        'genre': ['Novel', 'Humor', 'Satire'],
        'publisher': 'Audible Studios',
        'language': 'English'
    },
    '8': {
        'id': '8',
        'title': 'The Three-Body Problem',
        'coverImage': 'https://m.media-amazon.com/images/I/51pHYR3yHaL.jpg',
        'year': '2006',
        'summary': "Set against the backdrop of China's Cultural Revolution, a secret military project sends signals into space to establish contact with aliens. An alien civilization on the brink of destruction captures the signal and plans to invade Earth. Meanwhile, on Earth, different camps start forming, planning to either welcome the superior beings and help them take over a world seen as corrupt, or to fight against the invasion. The result is a science fiction masterpiece of enormous scope and vision.",
        'author': 'Cixin Liu',
        'price': '$14.95',
        'score': '4.3',
        'genre': ['Science fiction', 'Novel', 'Alien'],
        'publisher': 'Macmillan Audio',
        'language': 'Chinese'
    },
    '9': {
        'id': '9',
        'title': 'War and Peace',
        'coverImage': 'https://images-na.ssl-images-amazon.com/images/I/41Lwn9bf4tL._SX311_BO1,204,203,200_.jpg',
        'year': '1869',
        'summary': "From the breathless excitement of 16-year-old Natasha Rostov's first ball, to Prince Andrei Bolkonsky's epiphany on the battlefield at Austerlitz, the novel abounds in memorable incidents, particularly those involving Pierre Bezukhov. A seeker after moral and spiritual truths, Pierre and his search for life's deeper meaning stand at the heart of this monumental book. A tale of strivers in a world fraught with conflict, social and political change, and spiritual confusion, Tolstoy's magnificent work continues to entertain, enlighten, and inspire readers around the world.",
        'author': 'Leo Tolstoy',
        'price': '$9.30',
        'score': '4.5',
        'genre': ['War', 'Novel', 'Narrative', 'Patriotic', 'Hero'],
        'publisher': 'Dover Publications',
        'language': 'Russian'
    },
    '10': {
        'id': '10',
        'title': 'The Kite Runner',
        'coverImage': 'https://m.media-amazon.com/images/I/51tDeQ9XOPL.jpg',
        'year': '2003',
        'summary': "Taking us from Afghanistan in the final days of its monarchy to the present, The Kite Runner is the unforgettable and beautifully told story of the friendship between two boys growing up in Kabul. Raised in the same household and sharing the same wet nurse, Amir and Hassan grow up in different worlds: Amir is the son of a prominent and wealthy man, while Hassan, the son of Amir's father's servant, is a Hazara - a shunned ethnic minority. Their intertwined lives, and their fates, reflect the eventual tragedy of the world around them. When Amir and his father flee the country for a new life in California, Amir thinks that he has escaped his past. And yet he cannot leave the memory of Hassan behind him.The Kite Runner is a novel about friendship and betrayal, and about the price of loyalty. It is about the bonds between fathers and sons, and the power of fathers over sons - their love, their sacrifices, and their lies. Written against a backdrop of history that has not been told in fiction before, The Kite Runner describes the rich culture and beauty of a land in the process of being destroyed. But through the devastation, Khaled Hosseini offers hope for redemption.",
        'author': 'Khaled Hosseini',
        'price': '$13.99',
        'score': '4.7',
        'genre': ['War', 'Family', 'Nationality', 'Realistic'],
        'publisher': 'Simon & Schuster Audio',
        'language': 'English'
    }
}